# Generated by Django 6.0.7 on 2026-07-31 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='reading_time',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='views',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
