# Generated by Django 6.0.7 on 2026-08-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0002_remove_essay_tags_remove_essay_reading_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='language',
        ),
        migrations.AlterField(
            model_name='essay',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20),
        ),
    ]
